modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Crying%20Portals"
logoFile="icon.png"

[[mods]]
modId="cryingportals"
version="2.7"
displayName="Crying Portals"
displayURL="https://serilum.com/mod/crying-portals"
authors="Rick South"
description='''Extends the blocks allowed for nether portal creation to use normal and crying obsidian.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.cryingportals]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cryingportals]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "cryingportals.mixins.json"