modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Crying%20Portals"
logoFile="icon.png"

[[mods]]
modId="cryingportals"
version="2.7"
displayName="Crying Portals"
displayURL="https://serilum.com/mod/crying-portals"
authors="Rick South"
description='''Extends the blocks allowed for nether portal creation to use normal and crying obsidian.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.cryingportals]]
    modId="collective"
    type="required"
    versionRange="[7.53,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cryingportals]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "cryingportals.mixins.json"